version: '3.8'
services:
   auth-service:
      build:
         context: ./auth-service
      ports:
         - '3000:3000'
      networks:
         - backend
      depends_on:
         - redis
         - postgres

   game-session-service:
      build:
         context: ./game-session-service
      ports:
         - '3001:3001'
         - '9230:9230' # Debugging port
      networks:
         - backend
      depends_on:
         - redis
         - postgres
      command: npx nodemon --signal SIGINT --inspect=0.0.0.0:9230 --nolazy "src/index.ts" # Run the debug script with Nodemon

   matchmaking-service:
      build:
         context: ./matchmaking-service
      volumes:
         - ./matchmaking-service:/usr/src/app
      ports:
         - '3002:3002'
         - '9229:9229' # Debugging port
      networks:
         - backend
      depends_on:
         - redis
         - postgres
      command: npx nodemon --signal SIGINT --inspect=0.0.0.0:9229 --nolazy "src/index.ts" # Run the debug script with Nodemon
   
   localstack:
      image: localstack/localstack
      container_name: localstack
      ports:
         - "4566:4566" # LocalStack Gateway
         - "4571:4571" # S3
      environment:
         - SERVICES=s3,dynamodb,apigateway
         - DEBUG=1
      volumes:
         - "./scripts:/etc/localstack/scripts" # Point to the new folder for utility scripts

   rabbitmq:
      image: rabbitmq:3-management
      ports:
         - "5672:5672"   # Default RabbitMQ port
         - "15672:15672" # Management UI
      environment:
         RABBITMQ_DEFAULT_USER: guest
         RABBITMQ_DEFAULT_PASS: guest
      networks:
         - backend
         
   redis:
      image: redis:latest
      ports:
         - '6379:6379'
      networks:
         - backend
      healthcheck:
         test: ['CMD', 'redis-cli', 'ping']
         interval: 10s
         timeout: 5s
         retries: 3
      volumes:
         - redis-data:/data

   postgres:
      image: postgres:latest
      container_name: postgres
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: password
         POSTGRES_DB: game_dbs
      ports:
         - '5432:5432'
      volumes:
         - pg-data:/var/lib/postgresql/data
      networks:
         - backend

networks:
   backend:
      driver: bridge
      
volumes:
   redis-data:
   pg-data:
