version: '3.8'
services:
   auth-service:
      image: maorte/auth-service:latest
      ports:
         - '3000:3000'
      networks:
         - backend
      environment:
         REDIS_HOST: /run/secrets/REDIS_HOST
         REDIS_PORT: /run/secrets/REDIS_PORT
      secrets:
         - REDIS_HOST
         - REDIS_PORT
      depends_on:
         - redis

   game-session-service:
      image: maorte/game-session-service:latest
      ports:
         - '3001:3001'
      networks:
         - backend
      environment:
         REDIS_HOST: /run/secrets/REDIS_HOST
         REDIS_PORT: /run/secrets/REDIS_PORT
      secrets:
         - REDIS_HOST
         - REDIS_PORT
      depends_on:
         - redis

   matchmaking-service:
      image: maorte/matchmaking-service:latest
      env_file:
         - .env
      volumes:
         - ./matchmaking-service:/usr/src/app
      ports:
         - '3002:3002'
         - '9229:9229' # Debugging port
      networks:
         - backend
      environment:
         REDIS_HOST: /run/secrets/REDIS_HOST
         REDIS_PORT: /run/secrets/REDIS_PORT
      secrets:
         - REDIS_HOST
         - REDIS_PORT
      depends_on:
         - redis
      command: npx nodemon --signal SIGINT --inspect=0.0.0.0:9229 --nolazy "src/index.ts" # Run the debug script with Nodemon

   redis:
      image: redis:latest
      ports:
         - '6379:6379'
      networks:
         - backend
      healthcheck:
         test: ['CMD', 'redis-cli', 'ping']
         interval: 10s
         timeout: 5s
         retries: 3
      volumes:
         - redis-data:/data

networks:
   backend:
      driver: overlay

volumes:
   redis-data:

secrets:
   REDIS_HOST:
      external: true
   REDIS_PORT:
      external: true
