version: '3.8'
services:

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  game-session-service:
    build:
      context: ./game-session-service
    ports:
      - "3001:3001"
    networks:
      - backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data

networks:
  backend:
    driver: bridge

volumes:
  redis-data: