# version: '3.4'

# services:
#   authservice:
#     image: authservice
#     build:
#       context: GameBackendMicroservices/auth-service
#       dockerfile: ./Dockerfile
#     environment:
#       NODE_ENV: production
#     ports:
#       - 3000:3000

version: '3.8'
services:

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3000:3000"
    networks:
      - backend

  game-session-service:
    build:
      context: ./game-session-service
    ports:
      - "3001:3001"
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  backend:
    driver: bridge
  